name: olympian
description: A new Flutter project.

version: 2.5.5+90

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  just_audio: ^0.9.28
  in_app_review: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.1
  audio_session: ^0.1.10
  carousel_slider: ^4.0.0
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.3.1
  firebase_remote_config: ^3.0.10
  flutter_cache_manager: ^3.3.0
  stack_appodeal_flutter: ^3.1.3-beta.3
  appmetrica_plugin: ^1.4.0
  package_info_plus: ^4.0.1
  webview_flutter: ^4.0.2
  dio: ^5.1.2
  in_app_purchase: ^3.1.1
  amplitude_flutter: ^3.14.0
  device_info_plus: ^9.0.1
  onesignal_flutter: ^5.1.0
  lottie: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animations/
    - assets/images/
    - assets/fonts/
    - assets/audio/
    - assets/data/data.json
    - assets/html/index.html

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/Alegreya_Sans/AlegreyaSans-Bold.ttf
          weight: 600
